### ISSUE TITLE
I have some question,please help me~~~

### ISSUE THREAD

**Issue by Followwind4567** [lucapiccolboni/crylogger#1]
I do all the things , but when i install my apk on emulator and run monkey, it told me no souch file "/tmp/application.cryptolog".I found it on deltas\libcore\ojluni\src\main\java\java\security\CRYLogger.java. I can not create that file, so i change the path to "/data/local/tmp/application.cryptolog". Will it works or something else i should do.Please~~~~~help~~~~help~~~~~

**Comment by lucapiccolboni** [comment]
Hi, I don't think you need to change the path of the file `application.cryptolog`. After running the application with `run.py`, the file should be located in the folder `/data/data/<app_package_name>/cache/`. If you don't find that file, then it means that the application hasn't used (yet) one of the Java classes that we have instrumented. Did you try to run the test application that is included in the folder `app-test`? Thanks!
