### ISSUE TITLE
How to solve the INSTALL_FAILED_NO_MATCHING_ABIS failure?

### ISSUE THREAD

**Issue by darwintree** [lucapiccolboni/crylogger#10]
I fetched some apks from some Android application stores, but met some problem when installing
```
---------------adb: failed to install /home/zhang/documents/code/crylogger/scripts/data/apks/com.ss.android.article.news_8.3.3.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```
It seems that the problem was caused because it uses the arm binaries.

However, [support_for_arm_binaries_on_android_9_and_11_system_images](https://developer.android.com/studio/releases/emulator#support_for_arm_binaries_on_android_9_and_11_system_images) says that

>If you were previously unable to use the Android Emulator because your app depended on ARM binaries, you can now use the Android 9 x86 system image or any Android 11 system image to run your app – it is no longer necessary to download a specific system image to run ARM binaries. These **Android 9** and **Android 11** system images support ARM by default and provide dramatically improved performance when compared to those with full ARM emulation.

I verified the document by downloading the android 9 and android 11 image from Android Studio, and then ran the Android Studio emulator and installed apk `com.ss.android.article.news_8.3.3.apk` successfully by running `adb install -g com.ss.android.article.news_8.3.3.apk`.

It seems that the android 9/11 x86 image could provided ARM compatibility but my compiled crylogger failed to do that.

Have you met the INSTALL_FAILED_NO_MATCHING_ABIS failure? And how do you solve it?
Thanks in advance.

**Comment by darwintree** [comment]
You can download the apk from [here](https://3b8637d9f6c334dab555e2afbdc16687.dlied1.cdntips.net/imtt.dd.qq.com/16891/apk/4DE2B9643B6FBFF9D96297DE015A59BE.apk?mkey=60ec1cc17c10adc8&f=5608&fsname=com.ss.android.article.news_8.3.3_8330.apk&csr=1bbd&cip=124.16.139.61&proto=https) (about 100m)

**Comment by lucapiccolboni** [comment]
Hi,

I've seen similar issues in the past. There are some applications that cannot be installed on the emulator due to missing libraries or other related problems. I haven't investigated in depth the issues related to native libraries.

I'm not sure why the application works with the Android 9 image from Android Studio. Even if it is still Android 9, the exact version might be slightly different with a better support for native libraries.

Thanks

**Comment by darwintree** [comment]
> Hi,
> 
> I've seen similar issues in the past. There are some applications that cannot be installed on the emulator due to missing libraries or other related problems. I haven't investigated in depth the issues related to native libraries.
> 
> I'm not sure why the application works with the Android 9 image from Android Studio. Even if it is still Android 9, the exact version might be slightly different with a better support for native libraries.
> 
> Thanks

Thank you for your reply. In the Oakland paper you mentioned that you "ran CRYLOGGER on 1780 Android apps". Did you directly download apks from the embedded Play Store in emulator? Or did you specify arm / x86 and download from other apk sources?

**Comment by lucapiccolboni** [comment]
I used an apk crawler (which was a Python script developed by someone else) that downloaded the apks of the apps from the Google Play Store. Unfortunately, I think it is no longer available... Then, I discarded the apps that were not working on the emulator (installation fails or execution fails).

Thanks!
