### ISSUE TITLE
How to migrate CRYLOGGER delta to other Android versions?

### ISSUE THREAD

**Issue by darwintree** [lucapiccolboni/crylogger#11]
It seems simply apply the changes in `scripts/delta` folder to AOSP source code would work. The problem is how to correctly modify `current.txt` and `openjdk_java_files.bp`.

Could you provide some advice about how to check the correction of the migration? 
By the way, is there any method to only build the changed module and apply the changes instead of building the whole AOSP from scratch ?
Thanks in advance

**Comment by lucapiccolboni** [comment]
Applying the changes in `delta` should be sufficient. If you already built the AOSP and you changed only the files in the directory `delta`, the Makefile should have the correct dependencies and it should be able to compile only what it is needed.

In the version of Android that I used, the file `current.txt` was generated automatically. When you change the Java files and try to compile, it should tell you that you need to update the API through the command `make update-api`. I think that this command takes care of generating the file `current.txt`. The original file `openjdk_java_files.bp` should be modified manually by adding all the Java files contained under the directory `delta`.

Thanks
