### ISSUE TITLE
Why the FileOutputStream is used instead of the native "android.util.Log" library ?

### ISSUE THREAD

**Issue by darwintree** [lucapiccolboni/crylogger#12]
I noticed in the implementation of CRYLOGGER, you used
```java
private static FileOutputStream stream;
```
to record the log instead of using the android.util.Log library.
What is the intent of this design?

Thanks in advance.

**Comment by lucapiccolboni** [comment]
Hi! We used `FileOutputStream` because we implemented everything within the boundary of the Java Library, without using any Android-specific class. This makes it easier to compile the code we added to the Java library. Thanks!
