### ISSUE TITLE
Is it possible to use this tool to detect a single Java file?

### ISSUE THREAD

**Issue by zicofish** [lucapiccolboni/crylogger#2]
As title. Thanks a lot ~~

**Comment by lucapiccolboni** [comment]
Hi, it's possible but it requires some manual work. I suggest (1) downloading the code of the Java library you need, (2) applying the modifications that you can find in this repository under `scripts/deltas/libcore/ojluni/src/main/java` (and choosing a location where the log should be generated; by default it should be the 'tmp' directory), and (3) running your app with the instrumented library. At that point you should be able to run the app, get the log file and use `scripts/check.py` to check the rules. Thanks!
