### ISSUE TITLE
cryptolog not found

### ISSUE THREAD

**Issue by kyangl** [lucapiccolboni/crylogger#5]
I have reviewed the other two issues about cryptolog, which should be located in /data/data/com.example.aes/cache, (I am using the example app right now) but still didn't figure out how to solve the problem I am facing. I have two problems listed below.

1. I am using a remote server and could run the emulator successfully. However, while pinning the application, I got stuck on the part "get the ID of the task of the application to pin". There is no output from grep command. Do you have any ideas what could cause this? Why there is no task ID of the app?
<img width="514" alt="Screen Shot 2021-06-06 at 4 20 26 PM" src="https://user-images.githubusercontent.com/47279121/120918707-5c688c80-c6e8-11eb-9b58-c08d8b5c8934.png">

2. I have omitted the last two steps of the part of pinning the application, and started to run monkey. The automated test was successful.
<img width="565" alt="Screen Shot 2021-06-06 at 4 31 16 PM" src="https://user-images.githubusercontent.com/47279121/120918770-afdada80-c6e8-11eb-9a9e-0e38002249fc.png">
But I was not able to find the cryptolog in /data/data/com.example.aes/cache. I have seen "aes.log" in one of the subdirectories (which implies that the app is actually running as expected??):
<img width="353" alt="Screen Shot 2021-06-06 at 4 36 50 PM" src="https://user-images.githubusercontent.com/47279121/120918801-d7ca3e00-c6e8-11eb-87d5-3bd1a589f793.png">
and I tried `git status` in android-emu/libcore directory.
<img width="554" alt="Screen Shot 2021-06-06 at 4 47 27 PM" src="https://user-images.githubusercontent.com/47279121/120918817-f03a5880-c6e8-11eb-8de2-7d6522073709.png">
Do you have any suggestions on this or have you been in the similar situation before? I would really appreciate your help!!

Thank you!

**Comment by lucapiccolboni** [comment]
Hi! Thank you!

1) I'm not sure what is going on with the pinning. Is the application opened on the emulator when the application pinning is attempted? Perhaps the [previous command](https://github.com/lucapiccolboni/crylogger/blob/b84ec4501dd74ab77037b310474191ba6fd6ac31/scripts/run.py#L104-L105) fails to launch the application for some reasons and `am` does not find it?

2) If I launch the command `git status` from the directory `libcore` this is the results:

```
Not currently on any branch.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ojluni/src/main/java/java/net/URL.java
	modified:   ojluni/src/main/java/java/security/KeyStore.java
	modified:   ojluni/src/main/java/java/security/MessageDigest.java
	modified:   ojluni/src/main/java/java/security/SecureRandom.java
	modified:   ojluni/src/main/java/java/security/Signature.java
	modified:   ojluni/src/main/java/java/util/Random.java
	modified:   ojluni/src/main/java/javax/crypto/Cipher.java
	modified:   ojluni/src/main/java/javax/crypto/spec/PBEKeySpec.java
	modified:   ojluni/src/main/java/javax/crypto/spec/PBEParameterSpec.java
	modified:   ojluni/src/main/java/javax/net/ssl/HttpsURLConnection.java
	modified:   ojluni/src/main/java/javax/net/ssl/SSLContext.java
	modified:   ojluni/src/main/java/javax/net/ssl/SSLSocketFactory.java
	modified:   openjdk_java_files.bp

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	ojluni/src/main/java/java/security/CRYLogger.java

no changes added to commit (use "git add" and/or "git commit -a")
```

Can you check if these files have been copied from `scripts/deltas`?

Thanks!

**Comment by kyangl** [comment]
Hi! Glad to hear from you!!
Thank you so much for this guidance! Since I have run some of the code manually, I might have skipped that step and did not have crylogger properly installed. However, after I copied the files from `scripts/deltas` (and I have the exact output as yours above while running `git status`), I have some problem installing the example app onto the emulator.
<img width="565" alt="Screen Shot 2021-06-07 at 10 08 32 PM" src="https://user-images.githubusercontent.com/47279121/121031427-e85be080-c7dc-11eb-82ba-d32a8e376af8.png">
I have met this error the last time I tried to install it (on the previous emulator), and after trying to install it multiple times, it finally worked. But this time, it did not work and always output this error message. I am wondering if this problem could be generalized or this is related to my setup -- I am using a remote server with no hardware acceleration and no window/visualization (but the emulator could be started as expected). Or maybe this is because of the unstableness of the emulator? Any suggestion on this is appreciated!

**Comment by lucapiccolboni** [comment]
Ok, thanks! Please make sure you also recompile `android-emu` before running the emulator again. This is not related to the issue you're experiencing, but I just wanted to make sure that the files you copied are properly installed.

I'm not sure why it can't install the application on the emulator. Can you please check with the command `adb devices` if the emulator is listed there? Also, it would be very helpful to see the emulator running to make sure it is not stuck.

**Comment by kyangl** [comment]
Thank you for the reminder! 

I think I might have overlooked the fact that the app has already been installed in the recompiled emulator. Now CRYLOGGER is working as expected. Thank you so much, it helps a lot!
