### ISSUE TITLE
OpenGapps is not available

### ISSUE THREAD

**Issue by tausiq** [lucapiccolboni/crylogger#7]
The OpenGapps version used in the `setup_opengapps.sh` is not available anymore. 

https://sourceforge.net/projects/opengapps/files/x86/20210127/open_gapps-x86-9.0-super-20210127.zip

However, 
https://sourceforge.net/projects/opengapps/files/x86/20210126/open_gapps-x86-9.0-super-20210126.zip is available. Do you think this version can be used?

**Comment by lucapiccolboni** [comment]
Yes. I think it is fine. The OpenGApps are updated frequently so the link in `setup_opengapps.sh` should be updated as well. Thanks.
