### ISSUE TITLE
Cound ' sdk_phone_x86-userdebug' be substituted by other target platforms?

### ISSUE THREAD

**Issue by darwintree** [lucapiccolboni/crylogger#8]
In the setup file, `lunch sdk_phone_x86-userdebug` is used for compiling android. 
Could `sdk_phone_x86-userdebug` be substituted by other target platforms? And why this target platform is chosen? 

Thanks in advance.

**Comment by lucapiccolboni** [comment]
Hi, I tested it only on that platform. I don't think there is something platform-specific in what we do, so it might work on other platforms (or with other targets), even though I'm not sure. Thanks!
